# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'System_Tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import threading
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 761, 571))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Server_status = QtWidgets.QWidget()
        self.tab_Server_status.setObjectName("tab_Server_status")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_Server_status)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 331, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(20, 60, 281, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_cpu = QtWidgets.QLabel(self.groupBox_2)
        self.label_cpu.setGeometry(QtCore.QRect(20, 30, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cpu.setFont(font)
        self.label_cpu.setObjectName("label_cpu")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_Utilization = QtWidgets.QLabel(self.groupBox_2)
        self.label_Utilization.setGeometry(QtCore.QRect(20, 130, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_Utilization.setFont(font)
        self.label_Utilization.setObjectName("label_Utilization")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(200, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_base_speed = QtWidgets.QLabel(self.groupBox_2)
        self.label_base_speed.setGeometry(QtCore.QRect(200, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_base_speed.setFont(font)
        self.label_base_speed.setObjectName("label_base_speed")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(110, 110, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_processes = QtWidgets.QLabel(self.groupBox_2)
        self.label_processes.setGeometry(QtCore.QRect(110, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_processes.setFont(font)
        self.label_processes.setObjectName("label_processes")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 190, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 210, 101, 17))
        self.label_10.setObjectName("label_10")
        self.label_core = QtWidgets.QLabel(self.groupBox_2)
        self.label_core.setGeometry(QtCore.QRect(150, 170, 67, 17))
        self.label_core.setObjectName("label_core")
        self.label_sockets = QtWidgets.QLabel(self.groupBox_2)
        self.label_sockets.setGeometry(QtCore.QRect(150, 190, 67, 17))
        self.label_sockets.setObjectName("label_sockets")
        self.label_architecture = QtWidgets.QLabel(self.groupBox_2)
        self.label_architecture.setGeometry(QtCore.QRect(150, 210, 67, 17))
        self.label_architecture.setObjectName("label_architecture")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_Server_status)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 10, 331, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar_2.setGeometry(QtCore.QRect(20, 60, 291, 31))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(20, 110, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_InUse = QtWidgets.QLabel(self.groupBox_3)
        self.label_InUse.setGeometry(QtCore.QRect(20, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_InUse.setFont(font)
        self.label_InUse.setObjectName("label_InUse")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(110, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_available = QtWidgets.QLabel(self.groupBox_3)
        self.label_available.setGeometry(QtCore.QRect(110, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_available.setFont(font)
        self.label_available.setObjectName("label_available")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(220, 110, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_free = QtWidgets.QLabel(self.groupBox_3)
        self.label_free.setGeometry(QtCore.QRect(220, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_free.setFont(font)
        self.label_free.setObjectName("label_free")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 41, 20))
        self.label_14.setObjectName("label_14")
        self.label_Total = QtWidgets.QLabel(self.groupBox_3)
        self.label_Total.setGeometry(QtCore.QRect(60, 30, 211, 20))
        self.label_Total.setObjectName("label_Total")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(20, 170, 67, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(20, 190, 67, 17))
        self.label_20.setObjectName("label_20")
        self.label_cached = QtWidgets.QLabel(self.groupBox_3)
        self.label_cached.setGeometry(QtCore.QRect(120, 170, 101, 17))
        self.label_cached.setObjectName("label_cached")
        self.label_buffers = QtWidgets.QLabel(self.groupBox_3)
        self.label_buffers.setGeometry(QtCore.QRect(120, 190, 111, 17))
        self.label_buffers.setObjectName("label_buffers")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_Server_status)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 270, 331, 241))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_hdd_total = QtWidgets.QLabel(self.groupBox_4)
        self.label_hdd_total.setGeometry(QtCore.QRect(20, 150, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_hdd_total.setFont(font)
        self.label_hdd_total.setObjectName("label_hdd_total")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(190, 120, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_hdd_available = QtWidgets.QLabel(self.groupBox_4)
        self.label_hdd_available.setGeometry(QtCore.QRect(190, 150, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_hdd_available.setFont(font)
        self.label_hdd_available.setObjectName("label_hdd_available")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(110, 120, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_hdd_inUse = QtWidgets.QLabel(self.groupBox_4)
        self.label_hdd_inUse.setGeometry(QtCore.QRect(110, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_hdd_inUse.setFont(font)
        self.label_hdd_inUse.setObjectName("label_hdd_inUse")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar_3.setGeometry(QtCore.QRect(20, 60, 281, 31))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_Server_status)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 270, 331, 241))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(20, 110, 81, 17))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(20, 130, 81, 17))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(20, 150, 101, 17))
        self.label_28.setObjectName("label_28")
        self.label_ip = QtWidgets.QLabel(self.groupBox_5)
        self.label_ip.setGeometry(QtCore.QRect(150, 110, 161, 17))
        self.label_ip.setObjectName("label_ip")
        self.label_boradcast = QtWidgets.QLabel(self.groupBox_5)
        self.label_boradcast.setGeometry(QtCore.QRect(150, 130, 171, 17))
        self.label_boradcast.setObjectName("label_boradcast")
        self.label_netmark = QtWidgets.QLabel(self.groupBox_5)
        self.label_netmark.setGeometry(QtCore.QRect(150, 150, 171, 17))
        self.label_netmark.setObjectName("label_netmark")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(20, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_Rx = QtWidgets.QLabel(self.groupBox_5)
        self.label_Rx.setGeometry(QtCore.QRect(20, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Rx.setFont(font)
        self.label_Rx.setObjectName("label_Rx")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(160, 50, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_Tx = QtWidgets.QLabel(self.groupBox_5)
        self.label_Tx.setGeometry(QtCore.QRect(160, 70, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Tx.setFont(font)
        self.label_Tx.setObjectName("label_Tx")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(20, 170, 101, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(20, 190, 101, 17))
        self.label_30.setObjectName("label_30")
        self.label_mac = QtWidgets.QLabel(self.groupBox_5)
        self.label_mac.setGeometry(QtCore.QRect(150, 170, 171, 17))
        self.label_mac.setObjectName("label_mac")
        self.label_gateway = QtWidgets.QLabel(self.groupBox_5)
        self.label_gateway.setGeometry(QtCore.QRect(150, 190, 151, 17))
        self.label_gateway.setObjectName("label_gateway")
        self.tabWidget.addTab(self.tab_Server_status, "")
        self.tab_Testing = QtWidgets.QWidget()
        self.tab_Testing.setObjectName("tab_Testing")
        self.groupBox = QtWidgets.QGroupBox(self.tab_Testing)
        self.groupBox.setGeometry(QtCore.QRect(60, 30, 591, 401))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_ping = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_ping.setGeometry(QtCore.QRect(150, 70, 401, 31))
        self.textEdit_ping.setObjectName("textEdit_ping")
        self.pushButton_ping = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ping.setGeometry(QtCore.QRect(460, 110, 89, 25))
        self.pushButton_ping.setObjectName("pushButton_ping")
        self.listView_Ping = QtWidgets.QListWidget(self.groupBox)
        self.listView_Ping.setGeometry(QtCore.QRect(40, 150, 511, 221))
        self.listView_Ping.setObjectName("listView_Ping")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(50, 76, 101, 21))
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.tab_Testing, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 0, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(440, 0, 81, 17))
        self.label_username.setObjectName("label_username")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 0, 67, 17))
        self.label.setObjectName("label")
        self.label_uptime = QtWidgets.QLabel(self.centralwidget)
        self.label_uptime.setGeometry(QtCore.QRect(600, 0, 141, 17))
        self.label_uptime.setObjectName("label_uptime")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 22))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionReboot = QtWidgets.QAction(MainWindow)
        self.actionReboot.setObjectName("actionReboot")
        self.actionShutdown = QtWidgets.QAction(MainWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuSystem.addAction(self.actionLogout)
        self.menuSystem.addAction(self.actionReboot)
        self.menuSystem.addAction(self.actionShutdown)
        self.menuSystem.addSeparator()
        self.menubar.addAction(self.menuSystem.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "CPU"))
        self.label_cpu.setText(_translate("MainWindow", "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz"))
        self.label_2.setText(_translate("MainWindow", "Utilization"))
        self.label_Utilization.setText(_translate("MainWindow", "100%"))
        self.label_4.setText(_translate("MainWindow", "Base speed"))
        self.label_base_speed.setText(_translate("MainWindow", "1.78 GHz"))
        self.label_6.setText(_translate("MainWindow", "Processes"))
        self.label_processes.setText(_translate("MainWindow", "1000"))
        self.label_8.setText(_translate("MainWindow", "Cores:"))
        self.label_9.setText(_translate("MainWindow", "Sockets:"))
        self.label_10.setText(_translate("MainWindow", "Architecture:"))
        self.label_core.setText(_translate("MainWindow", "4"))
        self.label_sockets.setText(_translate("MainWindow", "1"))
        self.label_architecture.setText(_translate("MainWindow", "x86_64"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Memory"))
        self.label_15.setText(_translate("MainWindow", "In use"))
        self.label_InUse.setText(_translate("MainWindow", "10GB"))
        self.label_17.setText(_translate("MainWindow", "Available"))
        self.label_available.setText(_translate("MainWindow", "1.78 GB"))
        self.label_21.setText(_translate("MainWindow", "Free"))
        self.label_free.setText(_translate("MainWindow", "10GB"))
        self.label_14.setText(_translate("MainWindow", "Total"))
        self.label_Total.setText(_translate("MainWindow", "8.00 GB"))
        self.label_19.setText(_translate("MainWindow", "Cached:"))
        self.label_20.setText(_translate("MainWindow", "Buffers:"))
        self.label_cached.setText(_translate("MainWindow", "4"))
        self.label_buffers.setText(_translate("MainWindow", "4"))
        self.groupBox_4.setTitle(_translate("MainWindow", "HDD"))
        self.label_5.setText(_translate("MainWindow", "Total"))
        self.label_hdd_total.setText(_translate("MainWindow", "10GB"))
        self.label_7.setText(_translate("MainWindow", "Available"))
        self.label_hdd_available.setText(_translate("MainWindow", "10GB"))
        self.label_23.setText(_translate("MainWindow", "In use"))
        self.label_hdd_inUse.setText(_translate("MainWindow", "10GB"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Network"))
        self.label_25.setText(_translate("MainWindow", "IP Address:"))
        self.label_26.setText(_translate("MainWindow", "broadcast:"))
        self.label_28.setText(_translate("MainWindow", "Netmark:"))
        self.label_ip.setText(_translate("MainWindow", "4"))
        self.label_boradcast.setText(_translate("MainWindow", "1"))
        self.label_netmark.setText(_translate("MainWindow", "netmark"))
        self.label_18.setText(_translate("MainWindow", "RX packets"))
        self.label_Rx.setText(_translate("MainWindow", "100000 bytes"))
        self.label_22.setText(_translate("MainWindow", "TX packets"))
        self.label_Tx.setText(_translate("MainWindow", "1000000 bytes"))
        self.label_29.setText(_translate("MainWindow", "Mac Address:"))
        self.label_30.setText(_translate("MainWindow", "Gateway:"))
        self.label_mac.setText(_translate("MainWindow", "mack"))
        self.label_gateway.setText(_translate("MainWindow", "gateway"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Server_status), _translate("MainWindow", "Server Status"))
        self.groupBox.setTitle(_translate("MainWindow", "Ping"))
        self.textEdit_ping.setPlaceholderText(_translate("MainWindow", "input IP Address or Url"))
        self.pushButton_ping.setText(_translate("MainWindow", "Ping"))
        self.label_27.setText(_translate("MainWindow", "IP Address"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Testing), _translate("MainWindow", "Testing"))
        self.label_3.setText(_translate("MainWindow", "Username :"))
        self.label_username.setText(_translate("MainWindow", "linux"))
        self.label.setText(_translate("MainWindow", "Uptime :"))
        self.label_uptime.setText(_translate("MainWindow", "00:00:00"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionReboot.setText(_translate("MainWindow", "Reboot"))
        self.actionShutdown.setText(_translate("MainWindow", "Shutdown"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

        self.actionLogout.triggered.connect(self.logOut)
        self.actionReboot.triggered.connect(self.restart)
        self.actionShutdown.triggered.connect(self.shutdown)
        
        self.pushButton_ping.clicked.connect(self.Ping)
        self.getUser()
        self.getTime()
        thread1 = threading.Thread(target= self.threadCPU)
        thread2 = threading.Thread(target= self.threadNetwork)
        thread3 = threading.Thread(target= self.threadNumProcess)
        thread4 = threading.Thread(target= self.threadMem)
        thread5 = threading.Thread(target= self.threadHdd)
        thread1.start()
        thread2.start()
        thread3.start()
        thread4.start()
        thread5.start()

    def threadCPU(self):
        while True:
            self.getCPUInfo()

            time.sleep(1)
    def threadNetwork(self):
        while True:
            self.getNetworkInfo()
            time.sleep(1)
    def threadNumProcess(self):
        while True:
            self.getNumProcess()
            time.sleep(1)
    def threadMem(self):
        while True:
            self.getMemInfo()
            time.sleep(1)
    def threadHdd(self):
        while True:
            self.getHDDInfo()
            time.sleep(1)

    def getCPUInfo(self):
        cmd = "top -b -d1 -n1|grep -i 'Cpu(s)'"
        cmd2 = "lscpu"
        result = os.popen(cmd)
        for line in result:
            percentage = int(round(float(line.strip().split()[1])))
            self.progressBar.setProperty("value", percentage)
            self.label_Utilization.setText(str(percentage) +"%")
        result2 = os.popen(cmd2)
        for line in result2:
            if "CPU MHz" in line:
                baseSpeed = float(line.strip().split(":")[1])/1000
                baseSpeed = '%.2f' %(baseSpeed)
                self.label_base_speed.setText(str(baseSpeed) +" GHz")
                break
            if "CPU(s):" in line:
                core  = line.strip().split(":")[1]
                self.label_core.setText(core.split()[0])
            if "Architecture" in line:
                arch = line.strip().split(":")[1]
                self.label_architecture.setText(arch.split()[0])
            if "Socket(s)" in line:
                sock = line.strip().split(":")[1]
                self.label_sockets.setText(sock.split()[0])
            if "Model name" in line:
                list = str(line.strip().split(":")[1]).split()
                cpu_model = ""
                for ls in list:
                    cpu_model += ls+" "
                self.label_cpu.setText(cpu_model)
                

    def getNumProcess(self):
        cmd = "ps -e --no-headers | wc -l"
        result = os.popen(cmd)
        for line in result:
            self.label_processes.setText(line.strip())
        
    def getMemInfo(self):
        total = 0.0
        available = 0.0
        cmd = "cat /proc/meminfo"
        result = os.popen(cmd)
        for line in result:
            if "MemTotal:" in line:
                total = float(line.strip().split()[1])/1000000
                total = '%.2f' %(total)
                self.label_Total.setText(str(total)+ "GB")
            if "MemFree:" in line:
                free = float(line.strip().split()[1])/1000000
                free = '%.2f' %(free)
                self.label_free.setText(str(free)+"GB")
            if "MemAvailable:" in line:
                available = float(line.strip().split()[1])/1000000
                available = '%.2f' %(available)
                self.label_available.setText(str(available)+"GB")
            if "Buffers:" in line:
                buffers = float(line.strip().split()[1])/1000
                buffers = '%.2f' %(buffers)
                self.label_buffers.setText(str(buffers)+"MB")
            if "Cached:" in line and "Swap" not in line:
                cached = float(line.strip().split()[1])/1000
                cached = '%.2f' %(cached)
                self.label_cached.setText(str(cached)+"MB")                
                break

        total = float(total)
        available = float(available)
        memInUse =total - available
        memInUse = '%.2f' %(memInUse)
        self.label_InUse.setText(str(memInUse)+"GB")
        percentUsage = round((available*100)/total)
        self.progressBar_2.setProperty("value", percentUsage)
            
        
    def getHDDInfo(self):
        cmd = "df -hT /home"
        result = os.popen(cmd)
        for line in result:
            if "Filesystem" not in line:
                list_col = line.strip().split()
                total = list_col[2]+"B"
                used = list_col[3]+"B"
                avail = list_col[4]+"B"
                percent = list_col[5].split("%")[0]

                self.label_hdd_total.setText(total)
                self.label_hdd_inUse.setText(used)
                self.label_hdd_available.setText(avail)
                self.progressBar_3.setProperty("value",int(percent))
                
    def getNetworkInfo(self):
        cmd = "ifconfig"
        result = os.popen(cmd)
        for line in result:
            
            if "broadcast" in line:
                list_col = line.strip().split()
                ip_address = list_col[1]
                netmark =    list_col[3]
                broadcast =  list_col[5]
                self.label_ip.setText(ip_address)
                self.label_netmark.setText(netmark)
                self.label_boradcast.setText(broadcast)
            if "ether" in line:
                mac = line.strip().split()[1]
                self.label_mac.setText(mac)
            if "RX packets" in line:
                list_col = line.strip().split()
                rxPackets = list_col[2]+" "+list_col[3]
                self.label_Rx.setText(rxPackets)
            if "TX packets" in line:
                list_col = line.strip().split()
                txPackets = list_col[2]+" "+list_col[3]
                self.label_Tx.setText(txPackets)
                break
        cmd = "ip route show"
        result = os.popen(cmd)
        for line in result:
            if "default" in line:
                self.label_gateway.setText(line.strip().split()[2])
            
    def getUser(self):
        cmd = "whoami"
        result = os.popen(cmd)
        for line in result:
            self.label_username.setText(line.strip())

    def getTime(self):
        cmd = "uptime | awk '{ print $3 " " $4 }'"
        result = os.popen(cmd)
        time = ""
        for line in result:
            time = line.strip().split(",")
        time = time[0].split(":")
        if len(time)==1:
            self.label_uptime.setText(time[0])
        else:        
            self.label_uptime.setText(time[0]+" Hour "+time[1]+" Min")
        
    def Ping(self):
        print("ping")
        self.listView_Ping.clear()
        cmd = "ping -c 1 "+ self.textEdit_ping.toPlainText()
        result = os.popen(cmd)
        for line in result:
            self.listView_Ping.addItem(line)
    def logOut(self):
        cmd = "gnome-session-quit"
        result = os.popen(cmd)
        
    def restart(self):
        cmd = "/sbin/reboot"
        result = os.popen(cmd)
        
    def shutdown(self):
        cmd = "shutdown now"
        result = os.popen(cmd)
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
